# Uncomment the next line to define a global platform for your project
platform :ios, '18.5'

target 'TestingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod ‘Qualtrics’

  # Pods for TestingApp

end
